# nixpacks.toml

# Tell Nixpacks to use Node 22
[variables]
NIXPACKS_NODE_VERSION = "22"

[phases.setup]
# Don’t re-include "nodejs" or "openssl"—the Node provider already did that.
nixPkgs = ["postgresql"]
# If you need curl/wget you can drop into apt instead:
aptPkgs = ["curl", "wget"]

[phases.install]
dependsOn = ["setup"]
cmds = ["npm install"]

[phases.build]
dependsOn = ["install"]
cmds = [
  "npx prisma generate",
  "npm run build"
]
cacheDirectories = ["node_modules/.cache"]

# This is the _actual_ container entrypoint
[start]
cmd = "npx prisma migrate deploy && npm run start:prod"

